"use client";
import React, { createContext, useContext, useState } from "react";
import type { Language } from "@/types";

export const T = {
  th: {
    appName:"C&T AGROTECH", tagline:"Fertilizer Trading",
    trade:"เทรด", market:"ตลาด", portfolio:"พอร์ต", futures:"สัญญา",
    payment:"ชำระเงิน", news:"ข่าว", contact:"ติดต่อ", terms:"ข้อกำหนด",
    dashboard:"แดชบอร์ด", signIn:"เข้าสู่ระบบ", signUp:"สมัครสมาชิก", signOut:"ออกจากระบบ",
    darkMode:"โหมดมืด", language:"ภาษา",
    commodity:"สินค้า", symbol:"Symbol", lastPrice:"ราคาล่าสุด",
    change:"เปลี่ยนแปลง", volume24h:"Volume 24H", high24h:"สูงสุด 24H", low24h:"ต่ำสุด 24H",
    grade:"เกรด", origin:"แหล่งผลิต", category:"หมวดหมู่", unit:"หน่วย",
    orderBook:"Order Book", price:"ราคา (฿)", quantity:"จำนวน", total:"รวม",
    recentTrades:"ซื้อขายล่าสุด", midPrice:"ราคากลาง",
    placeOrder:"วางคำสั่ง", buy:"ซื้อ", sell:"ขาย",
    market_order:"Market", limit:"Limit", stop:"Stop",
    amount:"มูลค่ารวม", wallet:"กระเป๋าเงิน", sendOrder:"ส่งคำสั่ง",
    orderSent:"✓ ส่งแล้ว", productInfo:"ข้อมูลสินค้า", suppliers:"ผู้ขายแนะนำ",
    verified:"✓ ยืนยัน", trades:"ครั้ง",
    portfolioValue:"มูลค่าพอร์ต", profitLoss:"กำไร/ขาดทุน",
    liquidity:"เงินสด", todayPnl:"P&L วันนี้", holdings:"สินค้าที่ถือครอง",
    avgPrice:"ราคาเฉลี่ย", currentPrice:"ราคาปัจจุบัน", value:"มูลค่า",
    openOrders:"คำสั่งที่รอ", status:"สถานะ", side:"ฝั่ง", type:"ประเภท",
    futuresTitle:"สัญญาล่วงหน้า (Futures)", futuresDesc:"ล็อคราคาล่วงหน้าสูงสุด 12 เดือน",
    delivery:"ส่งมอบ", spotPrice:"Spot Price", futurePrice:"Future Price",
    premium:"Premium", openInterest:"Open Interest", buyContract:"ซื้อสัญญา",
    paymentTitle:"ระบบชำระเงิน", deposit:"ฝากเงิน", withdraw:"ถอนเงิน",
    txHistory:"ประวัติธุรกรรม", paymentMethod:"วิธีชำระเงิน",
    bankTransfer:"โอนธนาคาร", creditCard:"บัตรเครดิต", promptpay:"PromptPay",
    pending:"รอดำเนินการ", completed:"สำเร็จ", failed:"ล้มเหลว",
    email:"อีเมล", password:"รหัสผ่าน", confirmPassword:"ยืนยันรหัสผ่าน",
    fullName:"ชื่อ-นามสกุล", phone:"เบอร์โทรศัพท์",
    rememberMe:"จดจำฉัน", forgotPw:"ลืมรหัสผ่าน?",
    noAccount:"ยังไม่มีบัญชี?", hasAccount:"มีบัญชีแล้ว?",
    agreeTerms:"ยอมรับข้อกำหนดและเงื่อนไข",
    adminDashboard:"แดชบอร์ดผู้ดูแลระบบ", totalUsers:"ผู้ใช้ทั้งหมด",
    activeTraders:"นักเทรดที่ใช้งาน", totalVolume:"Volume 24H",
    totalTx:"ธุรกรรมทั้งหมด", pendingKYC:"รอ KYC", revenue:"รายได้ 30D",
    userMgmt:"จัดการผู้ใช้", role:"บทบาท", joinDate:"วันสมัคร", balance:"ยอดเงิน",
    contactTitle:"ติดต่อเรา", contactDesc:"ทีมงานพร้อมช่วยเหลือคุณ",
    yourName:"ชื่อของคุณ", subject:"หัวข้อ", message:"ข้อความ",
    sendMessage:"ส่งข้อความ", messageSent:"ส่งข้อความแล้ว!",
    address:"ที่อยู่", officeHours:"เวลาทำการ", lineId:"Line ID",
    termsTitle:"ข้อกำหนดการลงทุนและการบริหารความเสี่ยง",
    termsDesc:"กรุณาอ่านข้อกำหนดก่อนเริ่มซื้อขาย",
    newsTitle:"ข่าวตลาดสินค้าเกษตร",
    bullish:"ขาขึ้น", bearish:"ขาลง", neutral:"ทรงตัว",
    systemOnline:"ระบบทำงานปกติ", systemStatus:"สถานะระบบ",
    allocation:"สัดส่วนพอร์ต", accountSummary:"สรุปบัญชี",
  },
  en: {
    appName:"C&T AGROTECH", tagline:"Fertilizer Trading",
    trade:"Trade", market:"Market", portfolio:"Portfolio", futures:"Futures",
    payment:"Payment", news:"News", contact:"Contact", terms:"Terms",
    dashboard:"Dashboard", signIn:"Sign In", signUp:"Sign Up", signOut:"Sign Out",
    darkMode:"Dark Mode", language:"Language",
    commodity:"Commodity", symbol:"Symbol", lastPrice:"Last Price",
    change:"Change", volume24h:"Volume 24H", high24h:"High 24H", low24h:"Low 24H",
    grade:"Grade", origin:"Origin", category:"Category", unit:"Unit",
    orderBook:"Order Book", price:"Price (฿)", quantity:"Qty", total:"Total",
    recentTrades:"Recent Trades", midPrice:"Mid Price",
    placeOrder:"Place Order", buy:"Buy", sell:"Sell",
    market_order:"Market", limit:"Limit", stop:"Stop",
    amount:"Total Value", wallet:"Wallet", sendOrder:"Submit Order",
    orderSent:"✓ Submitted", productInfo:"Product Info", suppliers:"Top Suppliers",
    verified:"✓ Verified", trades:"trades",
    portfolioValue:"Portfolio Value", profitLoss:"Profit / Loss",
    liquidity:"Cash", todayPnl:"Today P&L", holdings:"Holdings",
    avgPrice:"Avg. Price", currentPrice:"Current Price", value:"Value",
    openOrders:"Open Orders", status:"Status", side:"Side", type:"Type",
    futuresTitle:"Futures Contracts", futuresDesc:"Lock in prices up to 12 months ahead",
    delivery:"Delivery", spotPrice:"Spot Price", futurePrice:"Future Price",
    premium:"Premium", openInterest:"Open Interest", buyContract:"Buy Contract",
    paymentTitle:"Payment System", deposit:"Deposit", withdraw:"Withdraw",
    txHistory:"Transaction History", paymentMethod:"Payment Method",
    bankTransfer:"Bank Transfer", creditCard:"Credit Card", promptpay:"PromptPay",
    pending:"Pending", completed:"Completed", failed:"Failed",
    email:"Email", password:"Password", confirmPassword:"Confirm Password",
    fullName:"Full Name", phone:"Phone Number",
    rememberMe:"Remember Me", forgotPw:"Forgot password?",
    noAccount:"Don't have an account?", hasAccount:"Already have an account?",
    agreeTerms:"I agree to the Terms & Conditions",
    adminDashboard:"Admin Dashboard", totalUsers:"Total Users",
    activeTraders:"Active Traders", totalVolume:"Volume 24H",
    totalTx:"Total Transactions", pendingKYC:"Pending KYC", revenue:"Revenue 30D",
    userMgmt:"User Management", role:"Role", joinDate:"Joined", balance:"Balance",
    contactTitle:"Contact Us", contactDesc:"Our team is ready to help you.",
    yourName:"Your Name", subject:"Subject", message:"Message",
    sendMessage:"Send Message", messageSent:"Message sent!",
    address:"Address", officeHours:"Office Hours", lineId:"Line ID",
    termsTitle:"Investment Terms & Risk Management",
    termsDesc:"Please read these terms carefully before trading.",
    newsTitle:"Agricultural Market News",
    bullish:"Bullish", bearish:"Bearish", neutral:"Neutral",
    systemOnline:"System Online", systemStatus:"System Status",
    allocation:"Allocation", accountSummary:"Account Summary",
  },
} as const;

type Tr = (typeof T)[keyof typeof T];

const LangCtx = createContext<{ lang: Language; setLang: (l: Language) => void; tr: Tr }>({
  lang: "th", setLang: () => {}, tr: T.th,
});

export function LangProvider({ children }: { children: React.ReactNode }) {
  const [lang, setLang] = useState<Language>("th");
  return <LangCtx.Provider value={{ lang, setLang, tr: T[lang] }}>{children}</LangCtx.Provider>;
}

export const useLang = () => useContext(LangCtx);
